import type { Metadata } from "next";
import { Kumar_One } from "next/font/google";
import "./globals.css";

const kumarOne = Kumar_One({
  weight: "400", // Kumar One only has 400
  subsets: ["latin"],
  variable: "--font-kumar-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kumarOne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
